kind: pipeline
name: default

steps:
- name: test
  pull: always
  image: brazildatacube/sits-base:0.12.0
  commands:
  - R -e 'pacman::p_load(desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends",][["package"]], install = T, update = F, character.only = T)'
  - R -e 'v<-gsub("(>) |(>=) ", "", desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends" & desc::desc_get_deps()[["version"]] != "*", ][["version"]]); pacman::p_install_version(package = desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends" & desc::desc_get_deps()[["version"]] != "*", ][["package"]], version = v)'
  - R CMD build .
  - set -e; R CMD check *.tar.gz --as-cran >&1 | tee stdfile && cat stdfile | (grep -E "(WARNING|ERROR)" > /dev/null) && exit 1 || exit 0

- name: coverage
  pull: always
  image: brazildatacube/sits-base:0.12.0
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    BDC_ACCESS_KEY:
      from_secret: bdc_token
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_key
    SITS_USER_CONFIG_FILE:
      from_secret: sits_user_config_file
  commands:
  - R -e 'pacman::p_load(desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends",][["package"]], install = T, update = F, character.only = T)'
  - R -e 'v<-gsub("\\\\D{1,}\\\\s", "", desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends" & desc::desc_get_deps()[["version"]] != "*", ][["version"]]); pacman::p_install_version(package = desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends" & desc::desc_get_deps()[["version"]] != "*", ][["package"]], version = v)'
  - R -e 'withr::with_envvar(c(NOT_CRAN="true"), covr::codecov(quiet = FALSE))'
  when:
    event:
    - push
