# Default Palette includes:
# Most classes of the "Brazilian Vegetation Manual" (IBGE,2001)
# IPCC AFOLU, PRODES, TerraClass project, IGBP Discover, Copernicus Global Land Cover

# Source https://htmlcolorcodes.com/color-chart/flat-design-color-chart/
# Colours partially adapted for Africa Standardized Terrestrial Ecosystems
# and 1970 U.S. Vegetation Map

colors:
    Tropical_Forest:
        # Oak-hickory-pine forest in US Veg Map
        Evergreen_Broadleaf_Forest  : &forest "#518940"
        # Forest
        Forest                      : *forest
        Closed_Forest               : *forest
        # Mixed Forest
        # Southern mixed forest in US Veg Map
        Open_Forest                 : &openforest "#53A145"
        Mixed_Forest                : *openforest
        Sparse_Forest               : *openforest
        # Southern floodplain forest in US Veg Map
        Riparian_Forest             : &riparian_forest "#8FADB1"
        Mountainside_Forest         : *forest
        #
        Seasonally_Flooded          : "#A3E4D7"
        # Dense Woodlands and similar
        # Oak-hickory forest in US Veg Map
        Woodland                    : &woodlands "#91AC41"
        Dense_Woodland              : *woodlands
        Woody_Savanna               : *woodlands
        Cerradao                    : *woodlands

    Wetland:
        # Based on "belize hole" palette from Flat Design Color Chart
        Water                       : "#2980B9"
        Wetland                     :  &wetlands "#96C8C8"
        Permanent_Wetland           :  *wetlands
        # Based on "peter river" palette from Flat Design Color Chart
        Mangrove                    : "#D4E6F1"

    Savanna:
        # Savanna and Cerrado
        # Bluestem praire in US Veg Map
        Savanna                     : &savanna "#a2d43f"
        Wooded_Grassland            : *savanna
        Cerrado_Strictu_Sensu       : *savanna
        Cerrado                     : *savanna
        # Wheatgrass-bluestem-needlegrass
        Campo_Cerrado               : &campo_cerrado "#c5ed42"
        Savanna_Parkland            : *campo_cerrado
        Open_Cerrado                : *campo_cerrado

    Deciduous_Tropical_Forests:
        # Caatinga and decidous tropical forest
        # Based on "green sea" palette of Flat Design Color Chart
        Caatinga                    : &caatinga "#ffc3ca"
        Deciduous_Forest            : *caatinga

    Planted_Forest:
        # Silviculture and Planted Forest
        # Northern hardwood
        Planted_Forest              : &planted_forest "#90cac8"
        Silviculture                : *planted_forest
        # Secondary Vegetation
        # Beech-maple forest
        Secondary_Vegetation        : "#9bd15e"

    Boreal_Temperate_Forests:
        # Based on "turquoise" palette of Flat Design Color Chart
        # Great lakes pine forest in US Veg Map
        Evergreen_Needleleaf_Forest  : &enf "#96b1b7"
        # Great lakes spruce-fir forest
        Deciduous_Needleleaf_Forest  : &dnf "#b9e8f8"
        # Pine-douglas fir forest
        Deciduous_Broadleaf_Forest   : &dnf "#55a3b7"

    Grassland:
        # California steppe
        Grassland                   : &grassland "#f6cc41"
        Steppe                      : *grassland
        Natural_Herbaceous          : *grassland
        # Pasture is a special case
        # Grama-buffalo grass
        Pasture                     : &pasture "#fae28c"
        Dense_Herbaceous            : *pasture
        Herbaceous_Vegetation       : *pasture

    Shrubland:
        # Based on "orange" palette of Flat Design Color Chart
        Closed_Shrubland            : &closed_shrubland "#fa586e"
        Wooded_Shrubland            : *closed_shrubland
        Dense_Shrubland             : *closed_shrubland
        Shrubland                   : &shrubland "#ffc3ca"
        Open_Shrubland              : *shrubland
        Sparse_Shrubland            : *shrubland
        Rocky_Savanna               : *shrubland

    Barren:
        # Based on "orange" palette of Flat Design Color Chart
        Barren                      : &barren "#FDEBD0"
        Sparsely_Vegetated          : *barren
        Natural_Non_Forested        : *barren
        Nat_NonVeg                  : *barren
        Natural_Non_Vegetated       : *barren
        Dunes                       : "#FEF9E7"

    Cropland:
        # Based on "carrot" palette from Flat Design Color Chart
        Cropland                    : &cropland "#F0B27A"
        Temporary_Crop              : *cropland
        Temporary_Agriculture       : *cropland
        Agriculture_1_cycle         : *cropland
        Cropland_1_cycle            : *cropland
        Agriculture_2_cycle         : &ag_2_cycle "#EB984E"
        Cropland_2_cycle            : *ag_2_cycle
        Semi_Perennial_Crop         : &semi_perennial_crop "#E67E22"
        # Sugarcane is semi perennial crop
        Sugarcane                   : *semi_perennial_crop
        Perennial_Crop              : &perennial_crop "#CA6F1E"
        Perennial_Agriculture.      : *perennial_crop
        Annual_Crop                 : *perennial_crop
        # Coffee is perennial agriculture
        Coffee                      : *perennial_crop

        # Soybean and its variations
        # Based on "orange" palette from Flat Design Color Chart
        Soybeans                    : &soy "#FAD7A0"
        Soy_Fallow                  : *soy
        Soy                         : *soy
        Soy_Sunflower               : "#F8C471"
        Soy_Millet                  : &soy_millet "#F5B041"
        Soy_Sorghum                 : *soy_millet
        Soy_Corn                    : "#D68910"
        Soy_Cotton                  : "#9C640C"

        # Other crops
        # Based on "pumpkin" palette from Flat Design Color Chart
        # Cotton
        Cotton                      : &cotton "#D35400"
        Fallow_Cotton               : *cotton
        Millet_Cotton               : *cotton
        # Grains
        Corn                        : &corn  "#DC7633"
        Maize                       : *corn
        Sorghum                     : &sorghum "#E59866"
        Millet                      : *sorghum
        Beans                       : "#EDBB99"
        Wheat                       : "#F6DDCC"
        # Based on "turquoise" palette of Flat Design Color Chart
        Rice                        : "#FBEEE6"

    Mosaic:
        # Mosaic classes use color 2 of "YlGn-9" Brewer palette
        Forest_Cropland_Mosaic     : "#F7FCB9"
        Cropland_Natural_Vegetation: "#F7FCB9"

    Deforestation:

        # Deforestation, Degradation, Mining
        # Based on "Alizarin" palette from Flat Design Color Chart
        Deforestation               : &deforestation "#ccbab4"
        Deforestation_Mask          : *deforestation
        Degradation                 : "#afc97f"
        # PRODES
        # Based on "Alizarin" palette from Flat Design Color Chart
        Burned_Area                 : &burned_area "#CB4335"
        ClearCut_Burn               : *burned_area
        ClearCut_Burned_Area        : *burned_area
        # Uses same colour as pasture
        # Color 52 - grama-tobosa shrubsteppe
        Cleared_Area                : &clear_cut_soil "#feaa7a"
        ClearCut_Soil               : *clear_cut_soil
        ClearCut_Bare_Soil          : *clear_cut_soil
        Bare_Soil                   : *clear_cut_soil
        # Based on "nephritis" palette of Flat Design Color Chart
        Highly_Degraded             : &clear_cut_deg "#D4EFDF"
        ClearCut_Veg                : *clear_cut_deg
        Clear_Cut_Vegetation        : *clear_cut_deg
        Clear_Cut_Veg               : *clear_cut_deg
        # Based on "amethyst" palette from Flat Design Color Chart
        Mining                      : "#C39BD3"
        # Based on "silver" palette from Flat Design Color Chart
        Non_Forest                  : "#BDC3C7"
    Urban:
        # Based on "wet asphalt" palette from Flat Design Color Chart
        Urban_Area                  : "#85929E"
    Snow_Ice:
        # Based on "asbestos" palette from Flat Design Color Chart
        Snow_Ice                    : &snow "#E5E8E8"
    Others:
        # No Class uses "silver" palette from Flat Design Color Chart
        No_Class                    : &no_class "#F2F3F4"
        No_Samples                  : *no_class
        Unclassified                : *no_class
        # Cloud uses "cloud" palette from Flat Design Color Chart
        Cloud                       : &cloud "#D0D3D4"

