# Internal configuration parameters - relevant only to sits developers
# s3 classes known to sits
sits_s3_classes :   ["sits", "patterns", "predicted", "sits_model",
                    "sits_cube", "raster_cube", "probs_cube",
                    "uncertainty_cube", "classified_image",
                    "wtss_cube", "satveg_cube",
                    "stac_cube", "bdc_cube", "aws_cube",
                    "usgs_cube", "deafrica_cube"]

# mandatory columns in data cube description
sits_cube_cols :    ["source", "collection", "satellite", "sensor",
                    "tile", "bands", "xmin", "xmax", "ymin", "ymax",
                    "crs", "labels"]

# mandatory columns in tibble description
sits_tibble_cols :  ["longitude", "latitude", "start_date",
                    "end_date", "label", "cube",
                    "time_series"]

# mandatory columns in predicted time series classification
ts_predicted_cols:  ["from", "to", "class"]

# supported user sample file formats
sample_file_formats : ["csv", "shp"]

# mandatory columns in CSV input files
csv_sample_columns : ["longitude", "latitude", "start_date", "end_date", "label"]

# possible som evaluations
som_outcomes    : ["clean", "analyze", "remove"]

# supported shp types
sf_geom_types_supported : ["POINT", "POLYGON", "MULTIPOLYGON"]

# local cube config options
local_s3_class          : ["local_cube", "raster_cube"]
local_file_extensions   : ["tiff", "tif", "jp2", "hdf", "vrt"]

# configuration for probability cubes
probs_cube_scale_factor : 0.0001
probs_cube_data_type    : "INT2U"

# configuration for classified cubes
class_cube_data_type    : "INT1U"

# simultaneous connections
cube_metadata_creation_n_workers : 4

# minimum requests to parallelize
cube_metadata_creation_minimum_items : 10

# valid aggregation methods for gdalcubes
gdalcubes_aggreg_methods : ["median", "stack"]

# valid resampling methods for gdalcubes
gdalcubes_resampling_methods : ["near", "bilinear", "bicubic", "cubicspline",
                                "lanczos"]

# valid raster data types
valid_raster_data_types : ["INT1U", "INT2U", "INT2S", "INT4U",
                          "INT4S", "FLT4S", "FLT8S"]

# deep learning activation methods
dl_activation_methods : ["relu", "elu", "selu", "sigmoid"]
